### ISSUE TITLE
Implementar Lektor para el Blog

### ISSUE THREAD

**Issue by javierdaza** [DjangoQuilla/django-quilla-web#6]
Implementar blog con [Lektor](https://www.getlektor.com/) u otro generador de plantillas estáticas en Python

**Comment by Scot3004** [comment]
Puedo hacerlo, si el objetivo es que quede igual a la página actual

**Comment by javierdaza** [comment]
Por supuesto. Si, el objetivo es que quede igual a la plantilla. Aunque pensé que se te hacia difícil

Crea un branch que se llame Lektor.

**Comment by Scot3004** [comment]
Bien, eso hare, jaja, para nada, y se configura lektor para que genere en el branch gh-pages 
eso ya lo tengo claro :) aprendi hace poco y me gusto este hosting jejeje

**Comment by javierdaza** [comment]
Según la plantilla hay una barra de búsquedas, eso todavía no es necesario.
Tampoco son necesarias las categorías por el momento

1. Las categorías tampoco es necesario adoptarlar por ahora
2. Dejemos los artículo recientes
3. Dejemos las etiquetas
4. Debe verse la Imagen previa de cada artículo (todos tienen los artículos tendrán imagen principal)
5. Debe verse el título del artículo (debe ser enlace también)
6. Debe verse la fecha del artículo
7. Debe verse el autor del artículo
8. Debe tener un texto de resumen del artículo
9. Enlace hacia el artículo
10. Separación entre artículos

Sobre cada artículo

1. Imagen principal
2. Fecha de publicacion del artículo
3. Quien publico el artículo
4. Cuerpo del artículo
5. Iconos de redes sociales (twitter y facebook)
6. Articulos recientes
7. Etiquetas de artículos

De la sección de comentarios me encargo yo.

@Scot3004 que opinas del plan?

**Comment by javierdaza** [comment]
@Scot3004 el PR de lektor 69ef5b6ab3ff07269371743905f91736e7d7082c debe resolver este issue.
